spring:
  application:
    name: tdd-practice

  docker:
    compose:
      enabled: false

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: